### ISSUE TITLE
Module3 Coursera project

### ISSUE THREAD

**Issue by lhudoba** [jhu-ep-coursera/fullstack-course1-module3#15]
When I type in  http://localhost:3000/courses/index, I get an error message

SON::ParserError in CoursesController#index
822: unexpected token at '<html> <head> <title>Coursera - API Route Does Not Exist</title> </head> <body style="background-color:#e4e4e4"> <div style="position:absolute; top:0; bottom:0; left:0; right:0; margin:auto; height:200px; width: 600px"> <div style="text-align:center"> <img src="https://s3.amazonaws.com/coursera/error_pages/coursera-logo.svg" width="400"> </div> <h1 style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:100; color: #555"> API Route Does Not Exist </h1> <div style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:300; font-size:13pt; color: #555"> Edge does not know about this API route. <br> Check whether this route is exposed in the routing table. </div> </div> </body> </html>'

I followed the earlier, 2017 jun post recommendation to change coursera API. to
        base_uri 'https://api.coursera.org/api//courses.v1'
	default_params fields: "photoURL,description", q: "search"
Is this correct?

**Comment by kalmanh** [comment]
Check out the following on the wiki - https://github.com/jhu-ep-coursera/fullstack-course1-module3/wiki#q-did-coursera-api-change

**Comment by kalmanh** [comment]
Also, check out the following 2 repos:

https://github.com/jhu-ep-coursera/random-countries-info

https://github.com/jhu-ep-coursera/book-searchy
