### ISSUE TITLE
error while creating a new gem

### ISSUE THREAD

**Issue by eniniz** [jhu-ep-coursera/fullstack-course1-module3#3]
hi 
when I tried to install a new gem a get that error :
ERROR:  Could not find a valid gem 'rspec' (>= 0) in any repository

**Comment by kalmanh** [comment]
What command did you run? Which OS are you using?

**Comment by eniniz** [comment]
Thanks’ for answering 
For OS I'm using windows 8 
And I run this command: gem install rspec

**Comment by kalmanh** [comment]
Please, ask for assistance on the discussion forums

https://www.coursera.org/learn/ruby-on-rails-intro/discussions?sort=lastActivityAtDesc&page=1
