### ISSUE TITLE
ExecJS::ProgramError in Greeter#hello

### ISSUE THREAD

**Issue by YaelSegal** [jhu-ep-coursera/fullstack-course1-module3#6]
Hi,
I try to enter "http://localhost:3000/greeter/hello"  after I add greeter controller but IA get the next error message : ExecJS::ProgramError in Greeter#hello.
I did exactly what you did In your lecture.
what can I do to make the page work?
![image](https://cloud.githubusercontent.com/assets/17783805/13703469/1c7a1888-e79f-11e5-9cbb-f2ea4e53f1e5.png)

**Comment by kalmanh** [comment]
https://github.com/jhu-ep-coursera/fullstack-course1-module1/wiki#q-how-to-fix-the-execjsprogramerror

**Comment by YaelSegal** [comment]
thanks, it works :), shabat shalom
