### ISSUE TITLE
Lesson03-Assignment01-HTTP-Client

### ISSUE THREAD

**Issue by YaelSegal** [jhu-ep-coursera/fullstack-course1-module3#7]
Hi,
I'm trying to do the first assignment and I get the next message:
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': 795: unexpected token at 'FORBIDDEN' (JSON::ParserError)

I don't know what to do...
i'm adding my code

require 'httparty'

class Recipe
    include HTTParty
    base_uri 'http://food2fork.com/api'
    default_params fields: "image_url,source_url,f2f_url,title,publisher_url,social_rank,page",key: ENV["FOOD2FORK_KEY"] 
    format :json
    def self.for term
         get("/search", query: { q: term})["elements"]  
    end
end

**Comment by kalmanh** [comment]
Please, ask your question on the Discussion forum

**Comment by Wonderband** [comment]
not ["elements"] but ["recipes"]
