### ISSUE TITLE
internal error when accessing food2fork

### ISSUE THREAD

**Issue by krzprz** [jhu-ep-coursera/fullstack-course1-module3#9]
I got :

Internal error

Ticket issued: F2F/78.11.43.106.2016-06-27.09-07-22.7c07beb1-ef2e-44f8-92ae-fed7fd8e6e59
Is it temporary or something is wrong with the site?

Thanks
Krzysiek

**Comment by kalmanh** [comment]
I believe (and hope :)) it's temporary. I've seen it happen before and usually it gets fixed pretty quickly.
